name: create PR

on:
  push:
    branches:
      - development
    tags:
      - release*
      - v1.*

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest version
        uses: actions/checkout@v2

      - name: Create PR
        uses: funivan/github-autopr@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

